// mockData.js
export const KEBSIHAN_REPORTS = [
    {
        id: '1',
        reporter: 'PIC001',
        location: 'Lorem ipsum dolor sit amet',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T10:00:00Z',
    },
    {
        id: '2',
        reporter: 'PIC002',
        location: 'Consectetur adipiscing elit',
        description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T11:30:00Z',
    },
    {
        id: '3',
        reporter: 'PIC003',
        location: 'Eiusmod tempor incididunt',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T13:00:00Z',
    },
    {
        id: '4',
        reporter: 'PIC004',
        location: 'Dolor sit amet',
        description: 'Consectetur adipiscing elit, sed do eiusmod tempor. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T14:00:00Z',
    },
    {
        id: '5',
        reporter: 'PIC005',
        location: 'Adipiscing elit',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T15:00:00Z',
    },
    {
        id: '6',
        reporter: 'PIC006',
        location: 'Sed do eiusmod',
        description: 'Duis aute irure dolor in reprehenderit in voluptate velit. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T16:00:00Z',
    },
    {
        id: '7',
        reporter: 'PIC007',
        location: 'Eiusmod tempor incididunt',
        description: 'Excepteur sint occaecat cupidatat non proident. Kebersihan',
        category: 'Kebersihan',
        createdAt: '2025-05-17T17:00:00Z',
    },
];

export const KELUHAN_REPORTS = [
    {
        id: '8',
        Reporter: 'Guest001',
        location: 'Ut labore et dolore',
        description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T14:45:00Z',
    },
    {
        id: '9',
        Reporter: 'Guest002',
        location: 'Magna aliqua minim veniam',
        description: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T16:00:00Z',
    },
    {
        id: '10',
        Reporter: 'Guest003',
        location: 'Magna aliqua minim veniam',
        description: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T17:00:00Z',
    },
    {
        id: '11',
        Reporter: 'Guest004',
        location: 'Tempor incididunt',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T18:00:00Z',
    },
    {
        id: '12',
        Reporter: 'Guest005',
        location: 'Dolore magna aliqua',
        description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T19:00:00Z',
    },
    {
        id: '13',
        Reporter: 'Guest006',
        location: 'Enim ad minim veniam',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T20:00:00Z',
    },
    {
        id: '14',
        Reporter: 'Guest007',
        location: 'Quis nostrud exercitation',
        description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse. Keluhan',
        category: 'Keluhan',
        createdAt: '2025-05-17T21:00:00Z',
    },
];